### ISSUE TITLE
切换意大利语后语音依然是英语

### ISSUE THREAD

**Issue by sylar605** [super-goodman/Diablo-Chinese#1]

**Comment by hyy34** [comment]
同上，语音只能设置英语 日语 韩语。英语是默认的，也非汉语。。CE不知道为什么，不好用了。

**Comment by hyy34** [comment]
> Diablo-Chinese.cpp 这行调整下： addrTemp = addrTemp + j+48; 重新编译，游戏界面，运行程序，然后选日语，语音 切换日语，就可以实现 文字和语音都是中文了。

额。有现成的下载吗？

**Comment by qingyaoyao789** [comment]
[链接: https://pan.baidu.com/s/16zIQnoorOn4p1Qh8XaQJnA?pwd=hwa1](url) 试一试能不能运行。第一次用vs2022编译.

**Comment by hyy34** [comment]
> [https://pan.baidu.com/s/16zIQnoorOn4p1Qh8XaQJnA?pwd=hwa1] 试一试能不能运行。第一次用vs2022编译.

找不到好多dll文件。
